### ISSUE TITLE
Backend service network not configurable

### ISSUE THREAD

**Issue by betsy-lichtenberg** [terraform-google-modules/terraform-google-lb-internal#54]
When I use example/simple and set the network to something other than "default" I get the following error:

Error: Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.backendService': 'https://www.googleapis.com/compute/v1/projects/project/regions/us-west1/backendServices/group-ilb-with-http-hc'. Forwarding rule network projects/project/global/networks/default must be the same as backend service network projects/project/global/networks/lb-network., invalid

When I tried modifying the backend service in [main.tf](https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/master/main.tf#L46) to include the network attribute and the load_balancing_scheme  = "INTERNAL", I get this error:

Error: Error updating RegionBackendService "projects/project/regions/us-west1/backendServices/group-ilb-with-http-hc": googleapi: Error 400: Invalid value for field 'resource.network': 'projects/project/global/networks/default'. Network field cannot be modified., invalid

**Comment by jmasparadigma** [comment]
Hi @betsy-lichtenberg, I tried modifing [maint.tf](https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/master/main.tf) outside the example in order to get it working. Something like this:
```
resource "google_compute_region_backend_service" "default" {
  project                         = var.project
  name                            = var.health_check["type"] == "tcp" ? "${var.name}-with-tcp-hc" : "${var.name}-with-http-hc"
  region                          = var.region
  protocol                        = var.ip_protocol
  timeout_sec                     = var.health_check["timeout_sec"] == null ? 10 : var.health_check["timeout_sec"]
  connection_draining_timeout_sec = var.connection_draining_timeout_sec
  session_affinity                = var.session_affinity
  load_balancing_scheme           = "INTERNAL"
  network                         = data.google_compute_network.network.self_link
  dynamic "backend" {
    for_each = var.backends
    content {
      group       = lookup(backend.value, "group", null)
      description = lookup(backend.value, "description", null)
    }
  }
  health_checks = [var.health_check["type"] == "tcp" ? google_compute_health_check.tcp[0].self_link : google_compute_health_check.http[0].self_link]
}
```

This allowed me to create the forwarding rule and the backend service in a Shared-VPC. I have to use the module locally though.

**Comment by aws2gcp** [comment]
Just curious - are you creating a new VPC network right before calling this module?

This is what I'm doing, and I'm also seeing it's somehow trying to use the 'default' network, which we do not use and is not defined in the project at all.  Oddly, the correct custom name does show up in plan/apply.  My best guess is the data source is partially failing and reverting to 'default'.  I'm able to correct the behavior by hard-coding the VPC network name when I call the module.

Some ideas on how this might be fixed:

- With ILBs, the network for the backend gets picked up from the instance group, correct?  So I don't see a need for the 'network' argument at all.  Personally I have never used it.

- If network argument is required, this should work fine: "projects/${coalesce(var.network_project, var.project)}/global/networks/${var.network}".  The data source seems unnecessary, since we already know the project and VPC network name.  
-

**Comment by jeheyer** [comment]
Just curious - are you creating a new VPC network right before calling this module?

This is what I'm doing, and I'm also seeing it's somehow trying to use the 'default' network, which we do not use and is not defined in the project at all. Oddly, the correct custom name does show up in plan/apply. My best guess is the data source is partially failing and reverting to 'default'. I'm able to correct the behavior by hard-coding the VPC network name when I call the module.

Some ideas on how this might be fixed:

- With ILBs, the network for the backend gets picked up from the instance group, correct?  So I don't see a need for the 'network' argument at all. Personally I have never used it.

- If network argument is required, this should work fine: "projects/${coalesce(var.network_project, var.project)}/global/networks/${var.network}". The data source seems unnecessary, since we already know the project and VPC network name.

**Comment by jeheyer** [comment]
Yeah, in that code, the network ID is passed explicitly from the resource that was created so that would solve the issue as well.

Anyhoo, I've had to cease using this module due to this behavior, but will drop some knowledge on this topic which may partially explain the root cause.  The Google [API documentation](https://cloud.google.com/compute/docs/reference/rest/v1/forwardingRules/insert) states the following:

_This field is not used for external load balancing. For Internal TCP/UDP Load Balancing, this field identifies the network that the load balanced IP should belong to for this Forwarding Rule. If this field is not specified, the default network will be used.  For Private Service Connect forwarding rules that forward traffic to Google APIs, a network must be provided._

There are two inaccuracies in this statement.  First, `network` **is** required for the external regional envoy-based HTTP(S) LBs, so that the correct REGIONAL_MANAGED_PROXY subnet can be determined.  Secondly, for internal TCP/UDP load balancers, it **is not** required at all and will default to the same network as the backend, not the "default" network (but there's no harm in providing `network` as long as the correct format is used).  

So, in the interests of KISS, I avoid the data query entirely by explicitly crafting the network ID using this format:

`
network = "projects/${coalesce(var.network_project, var.project)}/global/networks/${coalesce(var.network, "default")}"
`

Then only use that parameter if I'm dealing with an HTTP(S) LB.  This works 100% of the time regardless of circumstances.
