### ISSUE TITLE
"Simple" example creates a firewall rule with incorrect source ranges

### ISSUE THREAD

**Issue by betsy-lichtenberg** [terraform-google-modules/terraform-google-lb-internal#64]
group1-lb-hc has source ranges:

35.191.0.0/16
209.85.152.0/22
209.85.204.0/22

These are correct for external network load balancers, but not internal TCP/UDP load balancers.

For internal TCP/UDP load balancers, the source ranges should be:
35.191.0.0/16
130.211.0.0/22

For more info, see https://cloud.google.com/load-balancing/docs/health-checks#firewall_rules

**Comment by morgante** [comment]
The simple example *also* creates an external load balancer: https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/master/examples/simple/main.tf#L26

I'm guessing that's what you're seeing, because the firewall rule in this repo uses the correct ranges: https://github.com/terraform-google-modules/terraform-google-lb-internal/blob/master/main.tf#L148

**Comment by betsy-lichtenberg** [comment]
Got it, thanks.
